Repository RodSoriano/nekupu, pull requests merged in 2024-09, with the labels that each got.

#1 Modeling setup
  README.md
  app/api/src/app.module.ts
  app/api/src/entities/category.entity.ts
  app/api/src/entities/comment.entity.ts
  app/api/src/entities/contact.entity.ts
  app/api/src/entities/message.entity.ts
  app/api/src/entities/post.entity.ts
  app/api/src/entities/user.entity.ts
Labels: documentation, enhancement

#2 Added PWA setup
  app/api/src/entities/category.entity.ts
  app/api/src/entities/post.entity.ts
  app/frontend/angular.json
  app/frontend/ngsw-config.json
  app/frontend/package.json
  app/frontend/public/icons/icon-128x128.png
  app/frontend/public/icons/icon-144x144.png
  app/frontend/public/icons/icon-152x152.png
  app/frontend/public/icons/icon-192x192.png
  app/frontend/public/icons/icon-384x384.png
  app/frontend/public/icons/icon-512x512.png
  app/frontend/public/icons/icon-72x72.png
  app/frontend/public/icons/icon-96x96.png
  app/frontend/public/manifest.webmanifest
  app/frontend/src/app/app.config.ts
  app/frontend/src/index.html
  package.json
Labels: enhancement

#3 Adder seeder setup
  README.md
  app/api/.eslintignore
  app/api/database/config/typeorm.config.ts
  app/api/database/factories/category.factory.ts
  app/api/database/factories/comment.factory.ts
  app/api/database/factories/contact.factory.ts
  app/api/database/factories/post.factory.ts
  app/api/database/factories/user.factory.ts
  app/api/database/migrations/1727422804410-InitialMigration.ts
  app/api/database/seeder/category.seeder.ts
  app/api/database/seeder/comment.seeder.ts
  app/api/database/seeder/contact.seeder.ts
  app/api/database/seeder/init.seeder.ts
  app/api/database/seeder/post.seeder.ts
  app/api/database/seeder/user.seeder.ts
  app/api/package.json
  app/api/src/app.controller.spec.ts
  app/api/src/app.controller.ts
  app/api/src/app.module.ts
  app/api/src/category/category.controller.ts
  app/api/src/category/category.module.ts
  app/api/src/category/category.service.ts
  app/api/src/category/entities/category.entity.ts
  app/api/src/comment/comment.controller.ts
  app/api/src/comment/comment.module.ts
  app/api/src/comment/comment.service.ts
  app/api/src/comment/entities/comment.entity.ts
  app/api/src/comment/enums/comment-type.enum.ts
  app/api/src/common/entities/base-entity.entity.ts
  app/api/src/contact/contact.controller.ts
  app/api/src/contact/contact.module.ts
  app/api/src/contact/contact.service.ts
  app/api/src/contact/entities/contact.entity.ts
  app/api/src/entities/category.entity.ts
  app/api/src/entities/comment.entity.ts
  app/api/src/entities/contact.entity.ts
  app/api/src/entities/message.entity.ts
  app/api/src/entities/post.entity.ts
  app/api/src/entities/user.entity.ts
  app/api/src/main.ts
  app/api/src/message/entities/message.entity.ts
  app/api/src/message/message.controller.ts
  app/api/src/message/message.module.ts
  app/api/src/message/message.service.ts
  app/api/src/post/entities/post.entity.ts
  app/api/src/post/post.controller.ts
  app/api/src/post/post.module.ts
  app/api/src/post/post.service.ts
  app/api/src/user/entities/user.entity.ts
  app/api/src/user/user.controller.ts
  app/api/src/user/user.module.ts
  app/api/src/user/user.service.ts
Labels: bug, enhancement

#4 Added Chat implementation
  app/api/database/factories/chat-room.factory.ts
  app/api/database/factories/message.factory.ts
  app/api/database/migrations/1727508590850-ChatRoom.ts
  app/api/database/migrations/1727509120947-AddedChatRoomJoinColumn.ts
  app/api/database/seeder/chat-room.seeder.ts
  app/api/database/seeder/init.seeder.ts
  app/api/database/seeder/message.seeder.ts
  app/api/src/app.module.ts
  app/api/src/chat-room/chat-room.controller.ts
  app/api/src/chat-room/chat-room.module.ts
  app/api/src/chat-room/chat-room.service.ts
  app/api/src/chat-room/dto/create-chat-room.dto.ts
  app/api/src/chat-room/dto/update-chat-room.dto.ts
  app/api/src/chat-room/entities/chat-room.entity.ts
  app/api/src/message/entities/message.entity.ts
  app/api/src/user/entities/user.entity.ts
  app/frontend/angular.json
  app/frontend/src/app/app.component.html
  app/frontend/src/app/app.component.ts
  app/frontend/src/app/components/chat/chat.component.css
  app/frontend/src/app/components/chat/chat.component.html
  app/frontend/src/app/components/chat/chat.component.spec.ts
  app/frontend/src/app/components/chat/chat.component.ts
Labels: enhancement
